name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - wip
      - wip2
      - wip3
      - wip4
  pull_request:
    branches:
      - "**"

jobs:
  build-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.14.0

      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@cargo-lambda

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.8

      - name: Build Lambda Binary
        run: cargo lambda build --release --arm64
        working-directory: src/functions/client-rust
        env:
          SCCACHE_GHA_ENABLED: 'true'
          RUSTC_WRAPPER: 'sccache'

      - name: Upload Lambda Artifact
        uses: actions/upload-artifact@v4
        with:
          name: client-rust-lambda-arm64
          path: target/lambda/client-rust
          if-no-files-found: error

  deploy:
    needs: build-lambda
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Lambda Artifact
        uses: actions/download-artifact@v4
        with:
          name: client-rust-lambda-arm64
          path: target/lambda/client-rust

