name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - wip1
      - wip2
      - wip3
      - wip4
  pull_request:
    branches:
      - "**"

jobs:
  build-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Lambda Binary with Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: src/functions/client-rust/Dockerfile
          platforms: linux/arm64
          push: false
          outputs: type=local,dest=./build-output
          cache-to: type=gha,mode=max,scope=lambda-build
          cache-from: type=gha,scope=lambda-build
          target: export

      - name: Upload Lambda Artifact
        uses: actions/upload-artifact@v4
        with:
          name: client-rust-lambda-arm64
          path: build-output/
          if-no-files-found: error

  deploy:
    needs: build-lambda
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Lambda Artifact
        uses: actions/download-artifact@v4
        with:
          name: client-rust-lambda-arm64
          path: target/lambda/client-rust
